name: Update README

on:
  schedule:
    # æ¯å¤©è¿è¡Œä¸€æ¬¡
    - cron: "0 0 * * *"
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # æ£€å‡ºä»“åº“å†…å®¹
      - uses: actions/checkout@v3

      # ä½¿ç”¨ muesli/readme-scribe è‡ªåŠ¨ç”Ÿæˆ README.md
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      # è‡ªåŠ¨æäº¤æ›´æ–°åçš„ README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update generated README"
          branch: main
          commit_user_name: "readme-scribe ğŸ¤–"
          commit_user_email: "actions@github.com"
